blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # 绑定关系的写法是把网址和对应的处理函数作为参数传给 url 函数（第一个参数是网址r'^，第二个参数是处理函数views.index），
    # 另外我们还传递了另外一个参数 name，这个参数的值将作为处理函数 index 的别名，这在以后会用到。
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
    #     views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
          views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]


# 注意：在项目根目录的 blogproject\ 目录下（即 settings.py 所在的目录），原本就有一个 urls.py 文件，
# 这是整个工程项目的 URL 配置文件。而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。
# 这个文件将用于 blog 应用相关的 URL 配置。不要把两个文件搞混了。

blogproject/urls.py
# coding: utf-8
"""blogproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
# from django.conf.urls import url
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

#
# 我们这里导入了一个 include 函数，然后利用这个函数把 blog 应用下的 urls.py 文件包含了进来。
# 此外 include 前还有一个 r''，这是一个空字符串。这里也可以写其它字符串，
# Django 会把这个字符串和后面 include 的 urls.py 文件中的 URL 拼接。
# 比如说如果我们这里把 r'' 改成 r'blog/'，而我们在 blog.urls 中写的 URL 是 r'^$'，即一个空字符串。
# 那么 Django 最终匹配的就是 blog/ 加上一个空字符串，即 blog/。

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
    # url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
# coding: utf-8
import markdown
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags

# Create your models here.
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):

    # created_time = models.DateTimeField()
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    # 自定义get_absolute_url方法
    # 记得从django.urls中导入reverse函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']

# 注意到URL配置中的url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail') ，
# 我们设定的name = 'detail'在这里派上了用场。看到这个reverse函数，它的第一个参数的值是
# 'blog:detail'，意思是blog应用下的name = detail的函数，由于我们在上面通过app_name = 'blog'
# 告诉了Django这个URL模块是属于blog应用的，因此Django能够顺利地找到blog
# 应用下name为detail的视图函数，于是reverse函数会去解析这个视图函数对应的URL，我们这里
# detail对应的规则就是post / (?P < pk > [0 - 9] +) / 这个正则表达式，
# 而正则表达式部分会被后面传入的参数pk替换，所以，如果Post的id（或者pk，这里pk和id是等价的） 是
# 255的话，那么get_absolute_url函数返回的就是 / post / 255 / ，这样Post自己就生成了自己的
# URL。



# python_2_unicode_compatible 装饰器用于兼容 Python2
# created_time、modified_time。这两个列分别表示文章的创建时间和最后一次修改时间
# category和tags。这是分类与标签，分类与标签的模型我们已经定义在上面。
#
# ForeignKey
# 表明一种一对多的关联关系。比如这里我们的文章和分类的关系，一篇文章只能对应一个分类，
#
# ManyToManyField
# 表明一种多对多的关联关系，比如这里的文章和标签，一篇文章可以有多个标签，
# 而一个标签下也可以有多篇文章。反应到数据库表格中，它们的实际存储情况是这样的：

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

# 最后，这个评论是关联到某篇文章（Post）的，
# 由于一个评论只能属于一篇文章，一篇文章可以有多个评论，
# 是一对多的关系，因此这里我们使用了 ForeignKey。

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
# Create your views here.


# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     # post_list = Post.objects.all()
#     return render(request, 'blog/index.html', context={'post_list': post_list})


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')


# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
# 将category视图函数改为类视图
# 或者直接继承IndexView省略前三行代码
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year,  # time 与 year之间有两个下划线！！！created_time = models.DateTimeField()
#                                     created_time__month=month
#                                     ).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})


class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year =year,
                                                               created_time__month=month)


# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     post.increase_views()
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',
#                                       'markdown.extensions.toc',
#                                   ])
#     # 记得在顶部导入 CommentForm
#     form = CommentForm()
#     # 获取这篇 post 下的全部评论
#     comment_list = post.comment_set.all()
#
#     # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
#     context = {'post': post,
#                'form': form,
#                'comment_list': comment_list
#                }
#     return render(request, 'blog/detail.html', context=context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return post

    def get_context_data(self, **kwargs):
        # 覆写get_context_data的目的是因为除了将post传递给模板外（DetailView已经帮我们完成
        # 还要把评论表单,post下的评论列表传递给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

templates/blog/about.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>about</title>
</head>
<body>
    <h1>关于</h1>
    <p>这是一个人测试博客，欢迎评论。</p>
</body>
</html>

templates/blog/contact.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>contact</title>
</head>
<body>
    <h1>联系方式</h1>
    <p>xxxxxxxxx</p>
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
         <header class="entry-header">
            <h1 class="entry-title">
                <a class="text-primary">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{post.author}}</a></span>
                <span class="comments-link"><a href="#">{{comment_list.count}} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{post.body|safe}}
            <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}">#{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
         <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label for="{{ form.name.id_for_label }}">名字：</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                    </div>
                    <div class="col-md-6">
                        <label for="{{ form.email.id_for_label }}">邮箱：</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>
                    <!--<div class="col-md-4">-->
                        <!--<label for="{{ form.url.id_for_label }}">URL：</label>-->
                        <!--{{ form.url }}-->
                        <!--{{ form.url.errors }}-->
                    <!--</div>-->
                    <div class="col-md-12">
                        <label for="{{ form.text.id_for_label }}">评论：</label>
                        {{ form.text }}
                        {{ form.text.errors }}
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>    <!-- row -->
        </form>
            <div class="comment-list-panel">
            <h3>评论列表，共  <span>{{ post.comment_set.count }}</span>条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{comment.name}}</span>
                    <time class="submit-date">{{comment.created_time}}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
<link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
{% block main %}
    {% for post in post_list %}
{#        <div class="container">#}
            <div class="panel panel-default">
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}" class="text-primary" >{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">by {{ post.author }}</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                            <span class="comments-link">
                                <a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="post-category">
                                <a href="{% url 'blog:category' post.category.pk %}">分类：{{ post.category.name }}</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                            <a href="{{ post.get_absolute_url }} " class="text-primary" >完整文章 <span class="meta-nav">→</span></a>
                    </div>
                </article>
            </div>
{#        </div>#}
    {% empty %}
        <div class="no-post" >暂时还没有发布的文章！</div>
    {% endfor %}

    {% if is_paginated %}
        <div class="pagination-simple">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
            <!-- 显示当前页面信息 -->
            <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
            <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% endif %}
{##}
{#    <div class="pagination">#}
{#        <ul>#}
{#            <li><a href="">1</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">4</a></li>#}
{#            <li><a href="">5</a></li>#}
{#            <li class="current"><a href="">6</a></li>#}
{#            <li><a href="">7</a></li>#}
{#            <li><a href="">8</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">11</a></li>#}
{#        </ul>#}
{#    </div>#}
{% endblock main %}