blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # 绑定关系的写法是把网址和对应的处理函数作为参数传给 url 函数（第一个参数是网址r'^，第二个参数是处理函数views.index），
    # 另外我们还传递了另外一个参数 name，这个参数的值将作为处理函数 index 的别名，这在以后会用到。
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
    #     views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
          views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]


# 注意：在项目根目录的 blogproject\ 目录下（即 settings.py 所在的目录），原本就有一个 urls.py 文件，
# 这是整个工程项目的 URL 配置文件。而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。
# 这个文件将用于 blog 应用相关的 URL 配置。不要把两个文件搞混了。

blogproject/urls.py
# coding: utf-8
"""blogproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
# from django.conf.urls import url
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

#
# 我们这里导入了一个 include 函数，然后利用这个函数把 blog 应用下的 urls.py 文件包含了进来。
# 此外 include 前还有一个 r''，这是一个空字符串。这里也可以写其它字符串，
# Django 会把这个字符串和后面 include 的 urls.py 文件中的 URL 拼接。
# 比如说如果我们这里把 r'' 改成 r'blog/'，而我们在 blog.urls 中写的 URL 是 r'^$'，即一个空字符串。
# 那么 Django 最终匹配的就是 blog/ 加上一个空字符串，即 blog/。

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>ashdall</title>
    <link rel="shortcut icon" href="{% static 'favicon2.ico' %}" />
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!--<link rel="stylesheet" href="css/bootstrap.min.css">-->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!--<link rel="stylesheet" href="css/pace.css">-->
    <!--<link rel="stylesheet" href="css/custom.css">-->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <!-- js -->
    <!--<script src="js/jquery-2.1.3.min.js"></script>-->
    <!--<script src="js/bootstrap.min.js"></script>-->
    <!--<script src="js/pace.min.js"></script>-->
    <!--<script src="js/modernizr.custom.js"></script>-->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>ashdall</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

{#                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#                        <ul class="nav navbar-nav navbar-right">#}
{#                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>#}
{#                            <!--#href使用的blog下views中的函数-->#}
{#                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>#}
{#                        </ul>#}
{#                    </div><!-- /.navbar-collapse -->#}
                </nav>
{#                <div id="header-search-box">#}
{#                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>#}
{#                    <div id="search-form" class="search-form">#}
{#                        <form role="search" method="get" id="searchform" action="#">#}
{#                            <input type="search" placeholder="搜索" required>#}
{#                            <button type="submit"><span class="ion-ios-search-strong"></span></button>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <!--# 最新文章模板标签-->
                <div class="widdget-recent-posts">
                    <h3 class="widget-title">最新发布的文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url}}">{{post.title}}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <!--# 归档模板标签-->
                <div class="widget widget-archives">
                    <h3 class="widget-title">时间轴</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
                        </li>

                        {% empty %}
                        暂无归档内容！
                        {% endfor %}
                    </ul>
                </div>
                <!--# 分类模板标签-->
                <div calss="widget widget-category">
                    <h3 class="widget-title">文章分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>

                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>
                <!--# 标签云-->
                <div class = "widget widget-tag-cloud">
                    <h3 class="widget-title">标签</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}" class="text-warning" >{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签！
                        {% endfor %}
                    </ul>
                </div>
            <br>
            <br>
                <div class="jumbotron">
                    <div class="container">
                        <h1>欢迎！</h1>
                        <p><em>The radical optimists are willing to sacrifice everything to realize the dream of changing the world.</em></p>
                        <p><a href="https://docs.segmentfault.com/";  class="btn btn-primary btn-lg" role="button">
                         学习更多</a>
                        </p>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</div>
{#<footer id="site-footer">#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            <div class="col-md-12">#}
{#                <p class="copyright">&copy 2017 - 网页样式采集自<a href="http://www.cssmoban.com/"#}
{#                                                        target="_blank" title="模板之家">模板之家</a>#}
{#                </p>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</footer>#}

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<!--<script src="js/script.js"></script>-->
<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>